/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include <memory.h> /* for memset */
#include "tuplas.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

enum clnt_stat 
init_tuplas_1(int *clnt_res, CLIENT *clnt)
{
	 return (clnt_call (clnt, init_tuplas, (xdrproc_t) xdr_void, (caddr_t) NULL,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));

}

enum clnt_stat 
set_value_tuplas_1(message msg, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, set_value_tuplas,
		(xdrproc_t) xdr_message, (caddr_t) &msg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
get_value_tuplas_1(int key, message *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, get_value_tuplas,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_message, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
modify_value_tuplas_1(message msg, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, modify_value_tuplas,
		(xdrproc_t) xdr_message, (caddr_t) &msg,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
delete_key_tuplas_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, delete_key_tuplas,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}

enum clnt_stat 
exist_tuplas_1(int key, int *clnt_res,  CLIENT *clnt)
{
	return (clnt_call(clnt, exist_tuplas,
		(xdrproc_t) xdr_int, (caddr_t) &key,
		(xdrproc_t) xdr_int, (caddr_t) clnt_res,
		TIMEOUT));
}
