/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TUPLAS_H_RPCGEN
#define _TUPLAS_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct message {
	int key;
	char value1[256];
	int n_value2;
	double v_value2[32];
};
typedef struct message message;

#define TUPLAS 51258
#define TUPLASVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define init 1
extern  enum clnt_stat init_1(int *, CLIENT *);
extern  bool_t init_1_svc(int *, struct svc_req *);
#define set_value 2
extern  enum clnt_stat set_value_1(message , int *, CLIENT *);
extern  bool_t set_value_1_svc(message , int *, struct svc_req *);
#define get_value 3
extern  enum clnt_stat get_value_1(int , message *, CLIENT *);
extern  bool_t get_value_1_svc(int , message *, struct svc_req *);
#define modify_value 4
extern  enum clnt_stat modify_value_1(message , int *, CLIENT *);
extern  bool_t modify_value_1_svc(message , int *, struct svc_req *);
#define delete_key 5
extern  enum clnt_stat delete_key_1(int , int *, CLIENT *);
extern  bool_t delete_key_1_svc(int , int *, struct svc_req *);
#define exist 6
extern  enum clnt_stat exist_1(int , int *, CLIENT *);
extern  bool_t exist_1_svc(int , int *, struct svc_req *);
extern int tuplas_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init 1
extern  enum clnt_stat init_1();
extern  bool_t init_1_svc();
#define set_value 2
extern  enum clnt_stat set_value_1();
extern  bool_t set_value_1_svc();
#define get_value 3
extern  enum clnt_stat get_value_1();
extern  bool_t get_value_1_svc();
#define modify_value 4
extern  enum clnt_stat modify_value_1();
extern  bool_t modify_value_1_svc();
#define delete_key 5
extern  enum clnt_stat delete_key_1();
extern  bool_t delete_key_1_svc();
#define exist 6
extern  enum clnt_stat exist_1();
extern  bool_t exist_1_svc();
extern int tuplas_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TUPLAS_H_RPCGEN */
