/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TUPLAS_H_RPCGEN
#define _TUPLAS_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif


struct message {
	int key_or_return;
	char value1[256];
	int n_value2;
	double v_value2[32];
};
typedef struct message message;

#define TUPLAS 451258
#define TUPLASVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define init_tuplas 1
extern  enum clnt_stat init_tuplas_1(int *, CLIENT *);
extern  bool_t init_tuplas_1_svc(int *, struct svc_req *);
#define set_value_tuplas 2
extern  enum clnt_stat set_value_tuplas_1(message , int *, CLIENT *);
extern  bool_t set_value_tuplas_1_svc(message , int *, struct svc_req *);
#define get_value_tuplas 3
extern  enum clnt_stat get_value_tuplas_1(int , message *, CLIENT *);
extern  bool_t get_value_tuplas_1_svc(int , message *, struct svc_req *);
#define modify_value_tuplas 4
extern  enum clnt_stat modify_value_tuplas_1(message , int *, CLIENT *);
extern  bool_t modify_value_tuplas_1_svc(message , int *, struct svc_req *);
#define delete_key_tuplas 5
extern  enum clnt_stat delete_key_tuplas_1(int , int *, CLIENT *);
extern  bool_t delete_key_tuplas_1_svc(int , int *, struct svc_req *);
#define exist_tuplas 6
extern  enum clnt_stat exist_tuplas_1(int , int *, CLIENT *);
extern  bool_t exist_tuplas_1_svc(int , int *, struct svc_req *);
extern int tuplas_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define init_tuplas 1
extern  enum clnt_stat init_tuplas_1();
extern  bool_t init_tuplas_1_svc();
#define set_value_tuplas 2
extern  enum clnt_stat set_value_tuplas_1();
extern  bool_t set_value_tuplas_1_svc();
#define get_value_tuplas 3
extern  enum clnt_stat get_value_tuplas_1();
extern  bool_t get_value_tuplas_1_svc();
#define modify_value_tuplas 4
extern  enum clnt_stat modify_value_tuplas_1();
extern  bool_t modify_value_tuplas_1_svc();
#define delete_key_tuplas 5
extern  enum clnt_stat delete_key_tuplas_1();
extern  bool_t delete_key_tuplas_1_svc();
#define exist_tuplas 6
extern  enum clnt_stat exist_tuplas_1();
extern  bool_t exist_tuplas_1_svc();
extern int tuplas_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_message (XDR *, message*);

#else /* K&R C */
extern bool_t xdr_message ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_TUPLAS_H_RPCGEN */
